collectors:
  containerd:
    socket: /var/snap/microk8s/common/run/containerd.sock
driver:
  kind: ebpf
falco:
  json_output: true
falcosidekick:
  enabled: false
  webui:
    enabled: false
    service:
      type: NodePort
  config:
    elasticsearch:
      #Uncomment if deploying Elasticsearch to the cluster
      hostport: http://elasticsearch-master.monitoring.svc.cluster.local:9200
  image:
    registry: public.ecr.aws
tty: true
image:
  registry: public.ecr.aws
loader:
  image:
    registry: public.ecr.aws
customRules:
  customrules.yaml: |-
    - macro: user_known_ingress_remote_file_copy_activities
      condition: container.name startswith "hello-client" or k8s.ns.name = "monitoring"
