collectors:
  containerd:
    socket: //var/snap/microk8s/common/run/containerd.sock
driver:
  kind: ebpf
falco:
  json_output: true
falcosidekick:
  enabled: true
  webui:
    enabled: true
    service:
      type: NodePort
  config: 
    elasticsearch:
      #Uncomment if deploying Elasticsearch to the cluster
      #hostport: http://elasticsearch-master.monitoring.svc.cluster.local:9200
tty: true