collectors:
  containerd:
    socket: /var/snap/microk8s/common/run/containerd.sock
driver:
  kind: ebpf
falco:
  json_output: true
falcosidekick:
  enabled: true
  webui:
    enabled: true
    service:
      type: NodePort
    replicaCount: 1
  replicaCount: 1
tty: true
loader:
customRules:
  customrules.yaml: |-
    - macro: user_known_ingress_remote_file_copy_activities
      condition: container.name startswith "hello-client" or k8s.ns.name = "monitoring"